PACKAGE_NAME="bc250-amdgpu"
PACKAGE_VERSION="1.0"

AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="amdgpu"
BUILT_MODULE_LOCATION[0]="amd/amdgpu"
DEST_MODULE_LOCATION[0]="/updates"
DEST_MODULE_NAME[0]="amdgpu"

MAKE[0]="make -C ${kernel_source_dir} M=./amd/amdgpu modules"
CLEAN="rm -rf amd"

PRE_BUILD="prepare.sh ${kernelver} ${kernel_source_dir}"
